name: gp
channels:
  - defaults
  # - conda-forge
dependencies:
  - python=3.8
  - jupyterlab>=0.35.3
  - ipykernel>=5.0.1
  - matplotlib>=3.0.1
  - pandas>=0.23.4
  - scipy>=1.1.0
  - scikit-learn>=0.21.3
  - mkl>=2019.1
  - numpy>=1.15.4
  # - conda-forge::jupyter-dash
  # - flask-compress
  - plotly
  - tqdm
  - rise
  - ipywidgets
